name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2.5.0
      with:
        node-version: '14.x'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run bundle
      
    - name: GH Pages deploy
      # You may pin to the exact commit or the version.
      # uses: Cecilapp/GitHub-Pages-deploy@64837616f5938346d4be701112e6941195bfd54a
      uses: Cecilapp/GitHub-Pages-deploy@3.2.1
      with:
         # A verified email.
        email: 'sorokinvladislav1402@gmail.com'
          # Where static files are.
        build_dir: ./bundled
         # Which branch to push files.
        branch: 'gh-pages'
